### ISSUE TITLE
Create a glossary

### ISSUE THREAD

**Issue by j---** [CERTCC/CERT-Guide-to-CVD#2]
It would be convenient to have all the defined terms in one place. A glossary would be ideal. 
Secondary request is to have the document self-link, so that it's obvious when a term in the text is defined in the glossary.

**Comment by ahouseholder** [comment]
https://github.com/disclose/dioterms is a project that provides open-source vulnerability disclosure policies. While developing our glossary we should try to converge/harmonize on common definitions that are compatible with their resources as well.

**Comment by ahouseholder** [comment]
Clarify terms:

- reporting (finder to vendor, finder to coordinator, coordinator to vendor)
- publication (finder, vendor, coordinator to public)
- disclosure (both reporting and publication)

![Photo on 1-19-21 at 10 10 AM](https://user-images.githubusercontent.com/2594236/105054865-773faa80-5a40-11eb-9900-8f37c5327888.jpg)

**Comment by ahouseholder** [comment]
The mechanism for this is now in place as of #18 which created an [acronyms](https://raw.githubusercontent.com/CERTCC/CERT-Guide-to-CVD/main/docs/_includes/_acronyms.md) file that works with Material for MkDocs. Terms in that list get highlighted in the website automatically, see https://certcc.github.io/CERT-Guide-to-CVD/

- resolved by #18
